# arxivの学問領域の指定
subject: 'cat:cs.AI OR cat:cs.LG OR cat:cs.CL'

# 検索キーワード
keywords:
        kaggle: 1
        nlp: 1
        natural language processing: 1
        dialog: 1
        audio: 1
        speech: 1
        reinforcement: 1
        conversation: 1

# 通知の閾値
score_threshold: 0
